Coluna
ListaDupla Coluna::lista
Referenced by ColunaNomeada::getTamanho, ColunaArquivo::getTamanho, ColunaNomeada::imprimir, ColunaArquivo::imprimir, ColunaNomeada::inserirTarefa, ColunaArquivo::inserirTarefa, ColunaNomeada::moverTarefa, ColunaArquivo::moverTarefa, ColunaNomeada::obterTarefa, ColunaArquivo::obterTarefa, ColunaNomeada::ordenar, ColunaArquivo::ordenar, ColunaNomeada::removerTarefa, ColunaArquivo::removerTarefa.
virtual Coluna::~Coluna()
virtual void Coluna::inserirTarefa(Tarefa *t)=0
Insere uma tarefa na coluna.
t Ponteiro para a tarefa a ser inserida.
Referenced by adicionarTarefa, carregarQuadro, ColunaNomeada::moverTarefa, ColunaArquivo::moverTarefa.
virtual void Coluna::removerTarefa(int indice)=0
Remove uma tarefa da coluna.
indice Índice da tarefa a ser removida.
Referenced by removerTarefa.
virtual void Coluna::imprimir() const =0
Imprime as informações da coluna.
Referenced by Quadro::imprimir.
virtual void Coluna::moverTarefa(int indice, Coluna *colunaDestino)=0
Move uma tarefa de uma coluna para outra.
indice Índice da tarefa a ser movida. colunaDestino Ponteiro para a coluna de destino.
Referenced by moverTarefas.
virtual Tarefa * Coluna::obterTarefa(int indice)=0
Obtém uma tarefa da coluna pelo seu índice.
indice Índice da tarefa desejada. Ponteiro para a tarefa encontrada.
Referenced by editarTarefa, moverTarefas, salvarQuadro.
virtual int Coluna::getTamanho()=0
Obtém o tamanho da coluna, ou seja, a quantidade de tarefas nela contidas.
Tamanho da coluna.
Referenced by editarTarefa, moverTarefas, removerTarefa, salvarQuadro.
virtual string Coluna::getNome()=0
Obtém o nome da coluna.
Nome da coluna.
Referenced by Quadro::imprimir, salvarQuadro.
virtual string Coluna::getDescricao()=0
Obtém a descrição da coluna.
Descrição da coluna.
Referenced by salvarQuadro.
virtual void Coluna::setNome(string n)=0
Define o nome da coluna.
n Nome da coluna.
Referenced by editarColuna.
virtual void Coluna::setDescricao(string d)=0
Define a descrição da coluna.
d Descrição da coluna.
Referenced by editarColuna.
virtual void Coluna::ordenar()=0
Ordena as tarefas da coluna por prioridade.
Referenced by ordenarColuna.