main.cpp
void limparConsole()
Limpa a tela do console.
Referenced by main.
void clearBuffer()
Limpa o buffer do console.
Referenced by adicionarColunaArquivo, adicionarTarefa, cadastrarColaborador, criarColuna, criarQuadro, editarColuna, editarTarefa, main, moverColuna, moverTarefas, ordenarColuna, removerColuna, removerTarefa.
Colaborador * buscaBinaria(const set< Colaborador *, comparador > &equipe, int id)
Realiza uma busca binária em uma equipe de colaboradores pelo ID.
equipe O conjunto de colaboradores a ser pesquisado. id O ID do colaborador a ser encontrado. Um ponteiro para o colaborador encontrado ou nullptr se não for encontrado.
Referenced by adicionarTarefa, buscarColaborador, carregarQuadro, editarTarefa.
Colaborador * cadastrarColaborador(Quadro *&KanBan)
Cria e cadastra um novo colaborador no quadro KanBan.
KanBan O ponteiro para o quadro KanBan. O ponteiro para o novo colaborador cadastrado.
References clearBuffer, Quadro::inserirColaborador.
Referenced by adicionarTarefa, main.
void criarQuadro(Quadro *&KanBan)
Cria um novo quadro KanBan.
KanBan O ponteiro para o quadro KanBan a ser criado.
References clearBuffer.
Referenced by main.
void criarColuna(Quadro *&KanBan)
Cria e adiciona uma nova coluna ao quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References Quadro::adicionarColuna, clearBuffer.
Referenced by main.
void editarColuna(Quadro *&KanBan)
Edita uma coluna existente no quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References clearBuffer, Quadro::getNumeroColunas, Quadro::imprimir, Quadro::obterColuna, Coluna::setDescricao, Coluna::setNome.
Referenced by main.
void removerColuna(Quadro *&KanBan)
Remove uma coluna do quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References clearBuffer, Quadro::getNumeroColunas, Quadro::imprimir, Quadro::removerColuna.
Referenced by main.
void adicionarTarefa(Quadro *&KanBan)
Adiciona uma nova tarefa a uma coluna no quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References buscaBinaria, cadastrarColaborador, clearBuffer, Quadro::getEquipe, Quadro::getNumeroColunas, Quadro::imprimir, Coluna::inserirTarefa, Quadro::obterColuna, Tarefa::setPrioridade, Tarefa::setResponsavel.
Referenced by main.
void moverTarefas(Quadro *&KanBan)
Move uma tarefa de uma coluna para outra no quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References clearBuffer, Quadro::getNumeroColunas, Coluna::getTamanho, Quadro::imprimir, Coluna::moverTarefa, Quadro::obterColuna, Coluna::obterTarefa.
Referenced by main.
void editarTarefa(Quadro *&KanBan)
Edita uma tarefa existente no quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References buscaBinaria, clearBuffer, Quadro::getEquipe, Quadro::getNumeroColunas, Coluna::getTamanho, Quadro::imprimir, Quadro::obterColuna, Coluna::obterTarefa, Tarefa::setDescricao, Tarefa::setPrioridade, Tarefa::setResponsavel, Tarefa::setTitulo.
Referenced by main.
void removerTarefa(Quadro *&KanBan)
Remove uma tarefa de uma coluna no quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References clearBuffer, Quadro::getNumeroColunas, Coluna::getTamanho, Quadro::imprimir, Quadro::obterColuna, Coluna::removerTarefa.
Referenced by main.
void adicionarColunaArquivo(Quadro *&KanBan)
Adiciona uma nova coluna do tipo "arquivo" ao quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References Quadro::adicionarColuna, clearBuffer.
Referenced by main.
void moverColuna(Quadro *&KanBan)
Move uma coluna de uma posição para outra no quadro KanBan.
KanBan O ponteiro para o quadro KanBan.
References clearBuffer, Quadro::getNumeroColunas, Quadro::imprimir, Quadro::moverColuna.
Referenced by main.
void ordenarColuna(Quadro *&KanBan)
Ordena as tarefas por prioridade usando o algoritmo Bubble Sort.
Esta função implementa o algoritmo de ordenação conhecido como Bubble Sort (ou ordenação por flutuação). O algoritmo compara pares de elementos adjacentes e os troca de posição se estiverem fora de ordem, repetindo esse processo até que a lista esteja completamente ordenada. KanBan O ponteiro para o quadro KanBan. A complexidade do Bubble Sort é quadrática, O(n^2), onde n é o número de elementos na lista.
References clearBuffer, Quadro::getNumeroColunas, Quadro::imprimir, Quadro::obterColuna, Coluna::ordenar.
Referenced by main.
void exibirColaboradores(Quadro *&KanBan)
References Quadro::exibirColaboradores, Quadro::getEquipe.
Referenced by main.
void buscarColaborador(Quadro *&KanBan)
Busca um colaborador pelo ID no quadro KanBan e exibe suas informações.
Esta função realiza uma busca binária no vetor de colaboradores do quadro KanBan para encontrar um colaborador com o ID fornecido. O algoritmo de busca binária é utilizado devido à sua eficiência em listas ordenadas, reduzindo o número de comparações necessárias. KanBan O ponteiro para o quadro KanBan. A complexidade do algoritmo de busca binária é O(log n), onde n é o número de colaboradores no quadro.
References buscaBinaria, Quadro::getEquipe.
Referenced by main.
void salvarQuadro(Quadro *&KanBan, string fileName)
Salva o quadro KanBan em um arquivo.
KanBan O ponteiro para o quadro KanBan. fileName O nome do arquivo de saída.
References Tarefa::getDescricao, Quadro::getDescricao, Coluna::getDescricao, Quadro::getEquipe, Colaborador::getID, Quadro::getNome, Coluna::getNome, Quadro::getNumeroColunas, Tarefa::getPrioridade, Tarefa::getResponsavel, Coluna::getTamanho, Tarefa::getTitulo, Quadro::obterColuna, Coluna::obterTarefa.
Referenced by main.
Quadro * carregarQuadro(string fileName)
Carrega um quadro KanBan a partir de um arquivo.
fileName O nome do arquivo a ser carregado. O ponteiro para o quadro KanBan carregado.
References Quadro::adicionarColuna, buscaBinaria, Quadro::getEquipe, Quadro::inserirColaborador, Coluna::inserirTarefa.
Referenced by main.
int main()
References adicionarColunaArquivo, adicionarTarefa, buscarColaborador, cadastrarColaborador, carregarQuadro, clearBuffer, criarColuna, criarQuadro, editarColuna, editarTarefa, Quadro::exibirColaboradores, exibirColaboradores, Quadro::imprimir, limparConsole, moverColuna, moverTarefas, ordenarColuna, removerColuna, removerTarefa, salvarQuadro.