No
Tarefa* No::tarefa
Ponteiro para a tarefa armazenada no nó.
No* No::proximo
Ponteiro para o próximo nó.
No* No::anterior
Ponteiro para o nó anterior.
No::No(Tarefa *t)
Construtor da classe No.
t Ponteiro para a tarefa a ser armazenada no nó.
Tarefa * No::getTarefa() const
Obtém a tarefa armazenada no nó.
Ponteiro para a tarefa.
Referenced by ListaDupla::obterPorIndice, ListaDupla::ordenarPorPrioridade, ListaDupla::removerFim, ListaDupla::removerInicio, ListaDupla::removerPorIndice.
void No::setTarefa(Tarefa *t)
Define a tarefa a ser armazenada no nó.
t Ponteiro para a tarefa.
No * No::getProximo() const
Obtém o próximo nó.
Ponteiro para o próximo nó.
Referenced by ListaDupla::inserirInicio, ListaDupla::inserirPorIndice, ListaDupla::lightDelete, ListaDupla::obterPorIndice, ListaDupla::ordenarPorPrioridade, ListaDupla::removerInicio, ListaDupla::removerPorIndice.
void No::setProximo(No *p)
Define o próximo nó.
p Ponteiro para o próximo nó.
Referenced by ListaDupla::inserirFim, ListaDupla::inserirInicio, ListaDupla::inserirPorIndice, ListaDupla::lightDelete, ListaDupla::ListaDupla, ListaDupla::ordenarPorPrioridade, ListaDupla::removerFim, ListaDupla::removerInicio, ListaDupla::removerPorIndice.
No * No::getAnterior() const
Obtém o nó anterior.
Ponteiro para o nó anterior.
Referenced by ListaDupla::inserirFim, ListaDupla::inserirPorIndice, ListaDupla::lightDelete, ListaDupla::ordenarPorPrioridade, ListaDupla::removerFim, ListaDupla::removerPorIndice.
void No::setAnterior(No *a)
Define o nó anterior.
a Ponteiro para o nó anterior.
Referenced by ListaDupla::inserirFim, ListaDupla::inserirInicio, ListaDupla::inserirPorIndice, ListaDupla::lightDelete, ListaDupla::ListaDupla, ListaDupla::ordenarPorPrioridade, ListaDupla::removerFim, ListaDupla::removerInicio, ListaDupla::removerPorIndice.