Tarefa
string Tarefa::titulo
Título da tarefa
string Tarefa::descricao
Descrição da tarefa
int Tarefa::prioridade
Prioridade da tarefa
Colaborador* Tarefa::responsavel
Responsável pela tarefa
static string Tarefa::alinhamento(const string &texto, int width)
Alinha um texto ao centro de uma largura específica.
texto Texto a ser alinhado. width Largura do alinhamento. Texto alinhado.
static string Tarefa::quebrarLinha(const string &texto, int width)
Quebra o texto em várias linhas com base em uma largura específica.
texto Texto a ser quebrado. width Largura máxima de cada linha. Texto quebrado em várias linhas.
Tarefa::Tarefa()
Construtor padrão da classe Tarefa.
Tarefa::Tarefa(string t, string d)
Construtor da classe Tarefa.
t Título da tarefa. d Descrição da tarefa.
Tarefa::Tarefa(string t, string d, int p, Colaborador *r)
Construtor da classe Tarefa.
t Título da tarefa. d Descrição da tarefa. p Prioridade da tarefa. r Responsável pela tarefa.
Tarefa::~Tarefa()
Destrutor da classe Tarefa.
void Tarefa::setTitulo(string t)
Define o título da tarefa.
t Título da tarefa.
Referenced by editarTarefa.
void Tarefa::setDescricao(string d)
Define a descrição da tarefa.
d Descrição da tarefa.
Referenced by editarTarefa.
void Tarefa::setPrioridade(int p)
Define a prioridade da tarefa.
p Prioridade da tarefa.
Referenced by adicionarTarefa, editarTarefa.
void Tarefa::setResponsavel(Colaborador *r)
Define o responsável pela tarefa.
r Responsável pela tarefa.
Referenced by adicionarTarefa, editarTarefa.
string Tarefa::getTitulo()
Obtém o título da tarefa.
Título da tarefa.
Referenced by ColunaArquivo::imprimir, salvarQuadro.
string Tarefa::getDescricao()
Obtém a descrição da tarefa.
Descrição da tarefa.
Referenced by salvarQuadro.
int Tarefa::getPrioridade()
Obtém a prioridade da tarefa.
Prioridade da tarefa.
Referenced by ListaDupla::ordenarPorPrioridade, salvarQuadro.
Colaborador * Tarefa::getResponsavel()
Obtém o responsável pela tarefa.
Responsável pela tarefa.
Referenced by salvarQuadro.
std::ostream & operator<<(std::ostream &os, Tarefa *&tarefa)
Sobrecarga do operador de saída (<<) para imprimir as informações da tarefa.
os Fluxo de saída. tarefa Ponteiro para a tarefa a ser impressa. Fluxo de saída atualizado.