Quadro
std::string Quadro::nome
Nome do quadro.
std::string Quadro::descricao
Descrição do quadro.
Lista Quadro::listaColunas
Lista de colunas do quadro.
std::set<Colaborador *, comparador> Quadro::equipe
Equipe de colaboradores do quadro.
Quadro::Quadro()
Construtor padrão da classe Quadro.
Quadro::Quadro(const std::string &n, const std::string &d)
Construtor da classe Quadro.
n Nome do quadro. d Descrição do quadro.
Quadro::~Quadro()
Destrutor da classe Quadro.
References Lista::limpar.
void Quadro::adicionarColuna(Coluna *coluna)
Adiciona uma coluna ao quadro.
coluna Ponteiro para a coluna a ser adicionada.
References Lista::inserirInicio.
Referenced by adicionarColunaArquivo, carregarQuadro, criarColuna.
void Quadro::removerColuna(int indice)
Remove uma coluna do quadro.
indice Índice da coluna a ser removida.
References Lista::removerPorIndice.
Referenced by removerColuna.
Coluna * Quadro::obterColuna(int indice) const
Obtém uma coluna do quadro pelo índice.
indice Índice da coluna. Ponteiro para a coluna encontrada.
References Lista::obterPorIndice.
Referenced by adicionarTarefa, editarColuna, editarTarefa, imprimir, moverTarefas, ordenarColuna, removerTarefa, salvarQuadro.
int Quadro::getNumeroColunas() const
Obtém o número de colunas do quadro.
Número de colunas do quadro.
References Lista::getTamanho.
Referenced by adicionarTarefa, editarColuna, editarTarefa, imprimir, moverColuna, moverTarefas, ordenarColuna, removerColuna, removerTarefa, salvarQuadro.
std::string Quadro::getNome() const
Obtém o nome do quadro.
Nome do quadro.
Referenced by salvarQuadro.
std::string Quadro::getDescricao() const
Obtém a descrição do quadro.
Descrição do quadro.
Referenced by salvarQuadro.
void Quadro::setNome(std::string n)
Define o nome do quadro.
n Novo nome do quadro.
void Quadro::setDescricao(std::string d)
Define a descrição do quadro.
d Nova descrição do quadro.
std::set< Colaborador *, comparador > Quadro::getEquipe()
Obtém a equipe de colaboradores do quadro.
Equipe de colaboradores do quadro.
Referenced by adicionarTarefa, buscarColaborador, carregarQuadro, editarTarefa, exibirColaboradores, salvarQuadro.
void Quadro::imprimir() const
Imprime as informações do quadro.
References Coluna::getNome, getNumeroColunas, Coluna::imprimir, obterColuna.
Referenced by adicionarTarefa, editarColuna, editarTarefa, main, moverColuna, moverTarefas, ordenarColuna, removerColuna, removerTarefa.
void Quadro::inserirColaborador(Colaborador *colaborador)
Insere um colaborador na equipe do quadro.
colaborador Ponteiro para o colaborador a ser inserido.
Referenced by cadastrarColaborador, carregarQuadro.
void Quadro::exibirColaboradores()
Exibe os colaboradores da equipe do quadro.
Referenced by exibirColaboradores, main.
void Quadro::moverColuna(int indiceAntigo, int indiceNovo)
Move uma coluna do quadro para uma nova posição.
indiceAntigo Índice atual da coluna. indiceNovo Novo índice para a coluna.
References Lista::moverColuna.
Referenced by moverColuna.