ListaDupla
No* ListaDupla::sentinelaInicio
Ponteiro para o sentinela de início da lista.
No* ListaDupla::sentinelaFim
Ponteiro para o sentinela de fim da lista.
int ListaDupla::tamanho
Tamanho da lista.
ListaDupla::ListaDupla()
Construtor padrão da classe ListaDupla.
References No::setAnterior, No::setProximo.
ListaDupla::~ListaDupla()
Destrutor da classe ListaDupla.
References limpar.
int ListaDupla::getTamanho() const
Obtém o tamanho da lista.
Tamanho da lista.
Referenced by ColunaNomeada::getTamanho, ColunaArquivo::getTamanho, ColunaNomeada::imprimir, ColunaArquivo::imprimir.
bool ListaDupla::vazia() const
Verifica se a lista está vazia.
true se a lista estiver vazia, false caso contrário.
Referenced by limpar, removerFim, removerInicio.
void ListaDupla::inserirInicio(Tarefa *t)
Insere uma tarefa no início da lista.
t Ponteiro para a tarefa a ser inserida.
References No::getProximo, No::setAnterior, No::setProximo.
Referenced by inserirPorIndice.
void ListaDupla::inserirFim(Tarefa *t)
Insere uma tarefa no fim da lista.
t Ponteiro para a tarefa a ser inserida.
References No::getAnterior, No::setAnterior, No::setProximo.
Referenced by inserirPorIndice, ColunaNomeada::inserirTarefa, ColunaArquivo::inserirTarefa.
void ListaDupla::inserirPorIndice(Tarefa *t, int indice)
Insere uma tarefa na lista pelo índice.
t Ponteiro para a tarefa a ser inserida. indice Índice de inserção.
References No::getAnterior, No::getProximo, inserirFim, inserirInicio, No::setAnterior, No::setProximo.
void ListaDupla::removerInicio()
Remove a tarefa do início da lista.
References No::getProximo, No::getTarefa, No::setAnterior, No::setProximo, vazia.
Referenced by limpar, removerPorIndice.
void ListaDupla::removerFim()
Remove a tarefa do fim da lista.
References No::getAnterior, No::getTarefa, No::setAnterior, No::setProximo, vazia.
Referenced by removerPorIndice.
void ListaDupla::removerPorIndice(int indice)
Remove a tarefa da lista pelo índice.
indice Índice da tarefa a ser removida.
References No::getAnterior, No::getProximo, No::getTarefa, removerFim, removerInicio, No::setAnterior, No::setProximo.
Referenced by ColunaNomeada::removerTarefa, ColunaArquivo::removerTarefa.
void ListaDupla::lightDelete(int indice)
Remove a tarefa da lista, mas mantém o nó na lista sem referência à tarefa.
indice Índice da tarefa a ser removida.
References No::getAnterior, No::getProximo, No::setAnterior, No::setProximo.
Referenced by ColunaNomeada::moverTarefa, ColunaArquivo::moverTarefa.
void ListaDupla::limpar()
Remove todos os nós da lista e libera a memória.
References removerInicio, vazia.
Referenced by ~ListaDupla.
Tarefa * ListaDupla::obterPorIndice(int indice) const
Obtém a tarefa da lista pelo índice.
indice Índice da tarefa. Ponteiro para a tarefa encontrada.
References No::getProximo, No::getTarefa.
Referenced by ColunaNomeada::imprimir, ColunaArquivo::imprimir, ColunaNomeada::moverTarefa, ColunaArquivo::moverTarefa, ColunaNomeada::obterTarefa, ColunaArquivo::obterTarefa.
void ListaDupla::ordenarPorPrioridade()
Ordena a lista de tarefas por prioridade.
References No::getAnterior, Tarefa::getPrioridade, No::getProximo, No::getTarefa, No::setAnterior, No::setProximo.
Referenced by ColunaNomeada::ordenar, ColunaArquivo::ordenar.