Lista
NoSimples* Lista::inicio
Ponteiro para o primeiro nó da lista.
int Lista::tamanho
Tamanho da lista.
Lista::Lista()
Construtor da classe Lista.
Lista::~Lista()
Destrutor da classe Lista.
References limpar.
bool Lista::vazia() const
Verifica se a lista está vazia.
true se a lista estiver vazia, false caso contrário.
Referenced by limpar, removerInicio.
int Lista::getTamanho() const
Obtém o tamanho da lista.
Tamanho da lista.
Referenced by Quadro::getNumeroColunas.
void Lista::inserirInicio(Coluna *coluna)
Insere uma coluna no início da lista.
coluna Ponteiro para a coluna a ser inserida.
References NoSimples::proximo.
Referenced by Quadro::adicionarColuna.
void Lista::removerInicio()
Remove a coluna do início da lista.
References NoSimples::coluna, NoSimples::proximo, vazia.
Referenced by limpar, removerPorIndice.
void Lista::removerPorIndice(int indice)
Remove a coluna da lista pelo índice.
indice Índice da coluna a ser removida.
References NoSimples::coluna, NoSimples::proximo, removerInicio.
Referenced by Quadro::removerColuna.
void Lista::limpar()
Remove todos os nós da lista e libera a memória.
References removerInicio, vazia.
Referenced by ~Lista, Quadro::~Quadro.
Coluna * Lista::obterPorIndice(int indice) const
Obtém a coluna da lista pelo índice.
indice Índice da coluna. Ponteiro para a coluna encontrada.
References NoSimples::coluna, NoSimples::proximo.
Referenced by Quadro::obterColuna.
void Lista::moverColuna(int indiceAntigo, int indiceNovo)
Move uma coluna da lista de uma posição para outra.
indiceAntigo Índice atual da coluna. indiceNovo Novo índice da coluna.
References NoSimples::coluna, NoSimples::proximo.
Referenced by Quadro::moverColuna.